name: Documentation
on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        uses: bahmutov/npm-install@v1
      - name: Build docs
        run: "yarn build-storybook:docs"
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
