name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        uses: bahmutov/npm-install@v1
      - name: Yarn test
        run: "yarn test"
      - name: Percy test
        uses: percy/storybook-action@v0.1.1
        with:
          custom-command: "yarn snapshot"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
