name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # chromatic needs the full history to find ancestors

      - name: Set up .npmrc to use GitHub Packages for @envoy-scoped packages
        uses: actions/setup-node@v2
        with:
          registry-url: "https://npm.pkg.github.com"
          cache: "yarn"

      - name: Install dependencies
        run: yarn
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ENVOYBOT_PERSONAL_ACCESS_TOKEN }}

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Chromatic
        uses: chromaui/action@v1
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true

      - name: Percy
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        run: yarn snapshot
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
